server:
  port: 7050

#配置数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.3.135:30117/ldd_new
    username: root
    password: root
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: admin
    password: admin
  listener:
    type: simple
    simple:
      default-requeue-rejected: false
      acknowledge-mode: manual
#    virtual-host: /

mybatis-plus:
  type-handlers-package: com.yanggc