server:
  port: 7050
#配置数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.3.135:30117/ldd_new
    username: root
    password: root
mybatis-plus:
  type-handlers-package: com.yanggc